package kg.app.wwiiships.models;

public enum Country {

    AFGHANISTAN("Афганистан"),
    ALBANIA("Албания"),
    ALGERIA("Алжир"),
    ANDORRA("Андорра"),
    ANGOLA("Ангола"),
    ANTIGUA_DEPS("Антигуа и Барбуда"),
    ARGENTINA("Аргентина"),
    ARMENIA("Армения"),
    AUSTRALIA("Австралия"),
    AUSTRIA("Австрия"),
    AZERBAIJAN("Азербайджан"),
    BAHAMAS("Багамы"),
    BAHRAIN("Бахрейн"),
    BANGLADESH("Бангладеш"),
    BARBADOS("Барбадос"),
    BELARUS("Беларусь"),
    BELGIUM("Бельгия"),
    BELIZE("Белиз"),
    BENIN("Бенин"),
    BHUTAN("Бутан"),
    BOLIVIA("Боливия"),
    BOSNIA_HERZEGOVINA("Босния и Герцеговина"),
    BOTSWANA("Ботсвана"),
    BRAZIL("Бразилия"),
    BRUNEI("Бруней"),
    BULGARIA("Болгария"),
    BURKINA("Буркина-Фасо"),
    BURMA("Мьянма"),
    BURUNDI("Бурунди"),
    CAMBODIA("Камбоджа"),
    CAMEROON("Камерун"),
    CANADA("Канада"),
    CAPE_VERDE("Кабо-Верде"),
    CENTRAL_AFRICAN_REP("Центральноафриканская Республика"),
    CHAD("Чад"),
    CHILE("Чили"),
    CHINA("Китай"),
    REPUBLIC_OF_CHINA("Китай"),
    COLOMBIA("Колумбия"),
    COMOROS("Коморы"),
    DEMOCRATIC_REPUBLIC_OF_THE_CONGO("Демократическая Республика Конго"),
    REPUBLIC_OF_THE_CONGO("Конго"),
    COSTA_RICA("Коста-Рика"),
    CROATIA("Хорватия"),
    CUBA("Куба"),
    CYPRUS("Кипр"),
    CZECH_REPUBLIC("Чехия"),
    DANZIG("Данциг"),
    DENMARK("Дания"),
    DJIBOUTI("Джибути"),
    DOMINICA("Доминика"),
    DOMINICAN_REPUBLIC("Доминиканская Республика"),
    EAST_TIMOR("Восточный Тимор"),
    ECUADOR("Эквадор"),
    EGYPT("Египет"),
    EL_SALVADOR("Сальвадор"),
    EQUATORIAL_GUINEA("Экваториальная Гвинея"),
    ERITREA("Эритрея"),
    ESTONIA("Эстония"),
    ETHIOPIA("Эфиопия"),
    FIJI("Фиджи"),
    FINLAND("Финляндия"),
    FRANCE("Франция"),
    GABON("Габон"),
    GAZA_STRIP("Полоса Газа"),
    THE_GAMBIA("Гамбия"),
    GEORGIA("Грузия"),
    GERMANY("Германия"),
    GHANA("Гана"),
    GREECE("Греция"),
    GRENADA("Гренада"),
    GUATEMALA("Гватемала"),
    GUINEA("Гвинея"),
    GUINEA_BISSAU("Гвинея-Бисау"),
    GUYANA("Гайана"),
    HAITI("Гаити"),
    HOLY_ROMAN_EMPIRE("Священная Римская империя"),
    HONDURAS("Гондурас"),
    HUNGARY("Венгрия"),
    ICELAND("Исландия"),
    INDIA("Индия"),
    INDONESIA("Индонезия"),
    IRAN("Иран"),
    IRAQ("Ирак"),
    REPUBLIC_OF_IRELAND("Ирландия"),
    ISRAEL("Израиль"),
    ITALY("Италия"),
    IVORY_COAST("Кот-д'Ивуар"),
    JAMAICA("Ямайка"),
    JAPAN("Япония"),
    JONATHANLAND("Джонатанленд"),
    JORDAN("Иордания"),
    KAZAKHSTAN("Казахстан"),
    KENYA("Кения"),
    KIRIBATI("Кирибати"),
    NORTH_KOREA("Северная Корея"),
    SOUTH_KOREA("Южная Корея"),
    KOSOVO("Косово"),
    KUWAIT("Кувейт"),
    KYRGYZSTAN("Кыргызстан"),
    LAOS("Лаос"),
    LATVIA("Латвия"),
    LEBANON("Ливан"),
    LESOTHO("Лесото"),
    LIBERIA("Либерия"),
    LIBYA("Ливия"),
    LIECHTENSTEIN("Лихтенштейн"),
    LITHUANIA("Литва"),
    LUXEMBOURG("Люксембург"),
    MACEDONIA("Северная Македония"),
    MADAGASCAR("Мадагаскар"),
    MALAWI("Малави"),
    MALAYSIA("Малайзия"),
    MALDIVES("Мальдивы"),
    MALI("Мали"),
    MALTA("Мальта"),
    MARSHALL_ISLANDS("Маршалловы Острова"),
    MAURITANIA("Мавритания"),
    MAURITIUS("Маврикий"),
    MEXICO("Мексика"),
    MICRONESIA("Микронезия"),
    MOLDOVA("Молдова"),
    MONACO("Монако"),
    MONGOLIA("Монголия"),
    MONTENEGRO("Черногория"),
    MOROCCO("Марокко"),
    MOZAMBIQUE("Мозамбик"),
    NAMIBIA("Намибия"),
    NAURU("Науру"),
    NEPAL("Непал"),
    NETHERLANDS("Нидерланды"),
    NEW_ZEALAND("Новая Зеландия"),
    NICARAGUA("Никарагуа"),
    NIGER("Нигер"),
    NIGERIA("Нигерия"),
    NORWAY("Норвегия"),
    OMAN("Оман"),
    PAKISTAN("Пакистан"),
    PALAU("Палау"),
    PALESTINE("Палестина"),
    PANAMA("Панама"),
    PAPUA_NEW_GUINEA("Папуа – Новая Гвинея"),
    PARAGUAY("Парагвай"),
    PERU("Перу"),
    PHILIPPINES("Филиппины"),
    POLAND("Польша"),
    PORTUGAL("Португалия"),
    QATAR("Катар"),
    ROMANIA("Румыния"),
    RUSSIA("Россия"),
    RWANDA("Руанда"),
    ST_KITTS_NEVIS("Сент-Китс и Невис"),
    ST_LUCIA("Сент-Люсия"),
    SAINT_VINCENT_THE_GRENADINES("Сент-Винсент и Гренадины"),
    SAMOA("Самоа"),
    SAN_MARINO("Сан-Марино"),
    SAO_TOME_PRINCIPE("Сан-Томе и Принсипи"),
    SAUDI_ARABIA("Саудовская Аравия"),
    SENEGAL("Сенегал"),
    SERBIA("Сербия"),
    SEYCHELLES("Сейшелы"),
    SIERRA_LEONE("Сьерра-Леоне"),
    SINGAPORE("Сингапур"),
    SLOVAKIA("Словакия"),
    SLOVENIA("Словения"),
    SOLOMON_ISLANDS("Соломоновы острова"),
    SOMALIA("Сомали"),
    SOUTH_AFRICA("Южная Африка"),
    SOUTH_SUDAN("Южный Судан"),
    SPAIN("Испания"),
    SRI_LANKA("Шри-Ланка"),
    SUDAN("Судан"),
    SURINAME("Суринам"),
    SWAZILAND("Эсватини"),
    SWEDEN("Швеция"),
    SWITZERLAND("Швейцария"),
    SYRIA("Сирия"),
    TAIWAN("Тайвань"),
    TAJIKISTAN("Таджикистан"),
    TANZANIA("Танзания"),
    THAILAND("Таиланд"),
    TOGO("Того"),
    TONGA("Тонга"),
    TRINIDAD_TOBAGO("Тринидад и Тобаго"),
    TUNISIA("Тунис"),
    TURKEY("Турция"),
    TURKMENISTAN("Туркменистан"),
    TUVALU("Тувалу"),
    UGANDA("Уганда"),
    UKRAINE("Украина"),
    UNITED_ARAB_EMIRATES("Объединенные Арабские Эмираты"),
    UNITED_KINGDOM("Великобритания"),
    USA("Соединенные Штаты Америки"),
    URUGUAY("Уругвай"),
    UZBEKISTAN("Узбекистан"),
    VANUATU("Вануату"),
    VATICAN_CITY("Ватикан"),
    VENEZUELA("Венесуэла"),
    VIETNAM("Вьетнам"),
    WESTERN_SAHARA("Западная Сахара"),
    YEMEN("Йемен"),
    ZAMBIA("Замбия"),
    ZIMBABWE("Зимбабве");

    private String country;

    Country(String country) {
        this.country = country;
    }
}
